"""
Module 9 - ML Layer: Champion-Challenger (Track 3 add-on)

The deck's architecture describes a champion-challenger pattern: the
rule-based 5C scorecard (Modules 4-5) stays the CHAMPION - the score of
record, the one a credit manager actually acts on - while two ML models
run in parallel as CHALLENGERS, purely for monitoring and future
validation, never silently substituted in:

- Isolation Forest: unsupervised multivariate anomaly detection over the
  same submetric feature matrix Module 5 scores. Flags borrowers whose
  overall feature PROFILE is statistically unusual for this population,
  independent of whether their score is good or bad - a borrower can be
  perfectly healthy and still be an outlier (e.g. unusually large
  collateral value relative to turnover), which is exactly the kind of
  signal a rule-based scorecard structurally cannot surface, since it
  only ever looks at one submetric at a time.
- Gradient Boosting (HistGradientBoostingRegressor): a supervised
  challenger trained to predict a risk-proxy target from Module 3's raw
  features, independent of the champion's own weights/thresholds - see
  TARGET_BY_ARCHETYPE below for the one honesty caveat that matters most
  in this module.

Read the README before trusting any number this module produces.
"""

import os

DEFAULT_FEATURES_DIR = os.path.join(os.path.dirname(__file__), "..", "module3_feature_engineering", "features_output")
DEFAULT_SCORING_DIR = os.path.join(os.path.dirname(__file__), "..", "module5_scoring", "scoring_output")
DEFAULT_DATA_LAKE_DIR = os.path.join(os.path.dirname(__file__), "..", "module1_data_ingestion", "data_lake")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "ml_output")

# The 22 raw numeric submetrics Module 5 already scores (same set as
# module5_scoring/config.py's SCORING_SUBMETRICS, minus collateral_quality_
# score which is categorical-derived there - estimated_value_inr is used
# here instead as collateral's numeric signal). Both ML models see exactly
# this matrix - no feature the rule-based scorecard doesn't also see, so
# any divergence is a genuine "different model, same inputs" signal, not
# an artifact of the challenger having access to more data.
ML_FEATURE_COLUMNS = [
    # Capacity
    "current_ratio", "leverage_ratio", "dscr", "interest_coverage_ratio",
    "cash_flow_match_ratio", "revenue_cagr_3yr", "projected_revenue_growth_rate",
    "customer_concentration_pct", "supplier_concentration_pct",
    # Character
    "bureau_score", "civil_suit_years_since_active", "other_legal_dispute_years_since_active",
    "cheque_bounce_rate", "owner_time_in_business_years",
    # Capital
    "net_worth_to_assets_ratio",
    # Compliance
    "covenant_compliance_flag", "gst_ontime_filing_ratio", "utility_payment_timeliness",
    "epfo_ontime_remittance_ratio", "rent_payment_timeliness", "salary_payment_timeliness",
    # Collateral (numeric proxy; categorical type/construction_status not used - see README)
    "estimated_value_inr",
]

# --- Isolation Forest ---
ISOLATION_FOREST_PARAMS = {
    "n_estimators": 200,
    "contamination": 0.05,  # flag the most anomalous ~5% of the 400-borrower batch
    "random_state": 42,
}

# --- Gradient Boosting challenger ---
# THE key honesty caveat of this whole module: there is no real repayment/
# default outcome anywhere in this synthetic dataset (there are no loans
# that have actually been repaid or defaulted over time - Module 1
# generates a snapshot, not a loan-performance history). The hidden
# true_archetype label (healthy/stagnant/distressed) - generated by
# Module 1 to drive the synthetic data's internal consistency, and
# otherwise used ONLY for backtesting the rule-based scorecard's ordering
# in module3/module5's validate.py - is repurposed here as the closest
# available STAND-IN for a real repayment-outcome label, exactly as the
# deck's architecture answer already promised ("retrained via ... real
# repayment outcomes" - this is that slot, filled with the best proxy a
# synthetic dataset can offer). TARGET_BY_ARCHETYPE below is NOT a
# calibrated probability of default - it's an illustrative anchor so the
# regressor has a continuous target to fit, chosen to roughly track
# GRADE_BANDS' band centers. Swap this file's target-construction step for
# real observed repayment outcomes the day real loan performance data
# exists; nothing else in this module needs to change.
TARGET_BY_ARCHETYPE = {
    "healthy": 85.0,
    "stagnant": 55.0,
    "distressed": 20.0,
}

GRADIENT_BOOSTING_PARAMS = {
    "max_iter": 150,
    "max_depth": 4,
    "learning_rate": 0.08,
    "random_state": 42,
}

TRAIN_TEST_SPLIT_FRAC = 0.7
SPLIT_RANDOM_STATE = 42

# Verified by direct inspection (grouping borrower_features.csv by hidden
# true_archetype): projected_revenue_growth_rate has ZERO overlap between
# archetype groups in this synthetic dataset (distressed max -0.070,
# stagnant range 0.009-0.015, healthy min 0.096 - clean ~8-point gaps on
# both sides). Every other feature has realistic archetype overlap. This
# is a Module 1 data-generation artifact (that feature's archetype-
# conditioned noise is far tighter than the others'), not a Module 9 bug -
# it makes the full-feature-set challenger hit an implausible R2=1.0 /
# MAE=0.0 on held-out data, which would never happen on real data. Rather
# than quietly drop the feature from the deployed model (it's still a
# legitimately informative feature, same as any other), this second
# feature list is used ONLY for a secondary "what does the model learn
# from everything else" robustness/explainability run - see
# challenger_model.evaluate_holdout's docstring.
ROBUSTNESS_CHECK_FEATURE_COLUMNS = [c for c in ML_FEATURE_COLUMNS if c != "projected_revenue_growth_rate"]

# A borrower's champion (Module 5 composite_score) and challenger
# (Gradient Boosting) scores are flagged for manual review when they
# diverge by more than this many points on the shared 0-100 scale -
# exactly the "monitor divergence, don't auto-resolve it" behavior a real
# champion-challenger deployment uses.
#
# Recalibrated 15.0 -> 25.0 (user decision): at 15 points, 131/400 (33%)
# of borrowers were flagged - far too noisy for the flag to command any
# attention when it appears. At 25, ~35/400 (~9%) are flagged. Still an
# assumption, not calibrated against real outcomes (none exist in this
# synthetic dataset) - a production deployment recalibrates this against
# observed repayment data.
DIVERGENCE_FLAG_THRESHOLD = 25.0
