"""
Auto-generated, template-based (NOT LLM-generated) 2-3 line summary
explaining the composite score - which C scored highest/lowest and why,
drawn from data already computed upstream (Module 5's scores + Module 6's
own top-driver/exclusion notes). Consistent with this project's rule-based,
auditable-logic ethos: nothing here is inferred or generated by a model,
it's string assembly over numbers and notes that already exist.
"""

from config import DIMENSION_LABELS, RAG_GREEN_MIN, RAG_AMBER_MIN


def _rag_word(score):
    if score is None:
        return "unscored"
    if score >= RAG_GREEN_MIN:
        return "strong"
    if score >= RAG_AMBER_MIN:
        return "moderate"
    return "weak"


def build_commentary(record):
    composite = record.get("composite_score")
    grade = record.get("grade")
    dims = [d for d in record.get("dimensions", []) if d.get("score") is not None]

    if composite is None or not dims:
        return f"{record.get('borrower_id')} could not be scored - insufficient data across the 5 Cs (see segment note)."

    dims_sorted = sorted(dims, key=lambda d: d["score"])
    weakest = dims_sorted[0]
    strongest = dims_sorted[-1]

    parts = [f"{record.get('borrower_id')} scores {composite}/100 ({grade})."]

    strongest_label = DIMENSION_LABELS.get(strongest["key"], strongest["key"])
    weakest_label = DIMENSION_LABELS.get(weakest["key"], weakest["key"])

    strongest_reason = strongest.get("top_positive")
    strongest_clause = f", driven by {strongest_reason.lower()}" if strongest_reason else ""
    parts.append(
        f"{strongest_label} ({int(strongest['weight'] * 100) if strongest.get('weight') else 0}% weight) "
        f"is the strongest area at {strongest['score']}/100{strongest_clause}."
    )

    if weakest["key"] != strongest["key"]:
        weakest_note = weakest.get("note") or ""
        if weakest_note:
            weakest_clause = f" - {weakest_note.lower()}"
        else:
            weakest_reason = weakest.get("top_negative")
            weakest_clause = f", pulled down by {weakest_reason.lower()}" if weakest_reason else ""
        parts.append(
            f"{weakest_label} ({int(weakest['weight'] * 100) if weakest.get('weight') else 0}% weight) "
            f"is the weakest at {weakest['score']}/100{weakest_clause}."
        )

    return " ".join(parts)
